### PR TITLE
Email Validations

### LINKED ISSUE #14: Use regex to validate URL
Examine the way the url was written (or actually any other http status codes even...). 
i.e. "www.goggle.com" should raise a warning and through regex python (if we were using regex python) and then a suggestion based on that could emerge given how many characters we were off.

### LINKED ISSUE #29: Validate emails before sending
The emails (separated by comma) should be validated before calling the API to send emails.

### PR DESCRIPTION
**Pull request by aitikgupta**
This PR adds validations to individual emails separated by commas, and raises an alert displaying (one or more email addresses are incorrect).

This is currently all-or-nothing. We could easily perform a atleast-send-to-those-which-are-validated, but I believe this is more concrete in a never-failing conservative mindset.

Resolves #29

### CODE REVIEW

**Comment by MyrrhDev** [comment]
Hey! This is a nice feature that from what I gather validates that the person typing an email or emails to be sent the broken links to are "correct", yeah? At the very least that's not what issue #14 was about so maybe remove that and open a new issue.

**Comment by aitikgupta** [comment]
Oh wait, after going through the repository I came across https://github.com/MyrrhDev/Linker/blob/b408ba544b0c07a917420f7500f3316e5d973e5a/chrome-extension/foreground.js#L5-L12

I figured we're _already_ doing validations for URLs, but after testing the extension myself, I found the emails are not validated - and assumed that's what was meant by "validating the URLs".

Let me create another issue (maybe reassign me to that one?)

**Comment by MyrrhDev** [comment]
You're right, but if you notice this is a veeery basic validation that doesn't actually examine the *way* the url was written (or actually any other http status codes even...). i.e. "www.goggle.com" should raise a warning and through regex python (if we were using regex python) and then a suggestion based on that would emerge. Not your bad though, that other issue needs more detail! :)

**Comment by MyrrhDev** [comment]
Reassigned the new issue to you, thank you again! :)

**Pull request merged**
